config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions: 'users/sessions'}

  resources :users, only: [:show] do
    resources :items, only: [:create, :update, :destroy]
  end

  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end

  root 'welcome#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  default_scope { order('created_at ASC')}

  scope :incomplete_items, -> {Item.where(complete: false)}
  scope :complete_items, -> {Item.where(complete: true)}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @item = current_user.items.create(item_params)
    @item.expires_at = Time.now + 7.days

    if @item.save
      flash[:notice] = "Item was saved."
      redirect_to [@user]
    else
      flash[:alert] = "Try that again."
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.complete = !@item.complete
    @item.save!
    redirect_to current_user
  end

  def destroy
    @item = Item.find(params[:id])
    @user = User.find(params[:user_id])

    @item.destroy

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/item_helper.rb
module ItemHelper
  def incomplete_item
    Item.where(complete: false)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/.update.js.erb
<% if @item.saved? %>
  $('#item-<%= @item.id %>').hide();
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/items/_form.html.erb
<h4> Add an item </h4>

<%= form_for [user, user.items.new ] do |f| %>
  <div class="form-group">
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter a new item" %>
  </div>
  <%= f.submit "Submit Item", class: 'btn btn-default pull-right' %>
<% end %>

app/views/items/_item.html.erb
<div class="media" id='item-<%= item.id %>'>
  <div class="media-body">
    <p><strong><%= distance_of_time_in_words(Time.now, item.expires_at)%><%=" left before implosion || "%></strong>
      <%= item.name %>
      <% if item.complete %>
        <%= link_to "Mark Incomplete", user_item_path(item.user, item), method: :put, class: 'btn btn-success' %>
      <% else %>
        <%= link_to "Complete", user_item_path(item.user, item), method: :put, class: 'btn btn-success' %>
      <% end %>
        <%= link_to "Delete Item", user_item_path(item.user, item), method: :delete, remote: true, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this item?' }%>
      </p>
  </div>
</div>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-<%= @item.id %>').hide();
  $('#itemCount').html("<%= pluralize(@user.items.incomplete_items.count, 'thing') %>");
  $('.flash').prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button>The item -<%= @item.name %>- has been deleted!</div>");
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button>There was an error marking this as complete, try again</div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toboom</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <%= stylesheet_link_tag    'application', media: 'all' %>
      <%= javascript_include_tag 'application' %>
      <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <div class="pull-right user-info">
          <% if user_signed_in? %>
            <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> or <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
        </div>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> or
            <%= link_to "Sign in", new_user_session_path, :class => 'navbar-link' %>
          <% end %>
      </ul>
      <div class="flash">
       <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash.now[:alert] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash.now[:alert] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
      </div>

  <%= yield %>
    </div>
  </body>

  <div class="welcome">
    <% if user_signed_in? %>
      Welcome to your Toboom, <strong><%= current_user.email %></strong>
    <% end %>
  </div>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<br>
<br>
<div class="container">
  <div class="items">
    <h4>You have <span id='itemCount'><%= pluralize(@user.items.incomplete_items.count, 'thing') %></span> to do:</h4>
    <%= render @user.items.incomplete_items %>
  </div>

  <div class="item-form">
    <% if current_user %>
      <%= render partial: 'items/form',  locals: {user: @user} %>
    <% end %>
  </div>

  <div class="items">
    <h4> All your completed things: </h4>
    <%= render @user.items.complete_items %>
  </div>
</div>

app/views/welcome/index.html.erb
<br>
<br>
<div class="jumbotron">
  <h1>Toboom</h1>
  <h4>This is not an ordinary to-do app. Any item left for more than 7 days will implode.</h4>
  <br>
  <p> You must
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> or
    <%= link_to "Sign in", new_user_session_path, :class => 'navbar-link' %> to use this app
  </p>
</div>